# Generated by Django 4.1.5 on 2023-02-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, upload_to='projects/images/'),
        ),
    ]
