# Generated by Django 4.1.5 on 2023-02-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_project_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_images', models.ImageField(upload_to='about_me/images/')),
                ('about_intro', models.TextField()),
                ('about_p_one', models.TextField()),
                ('about_p_two', models.TextField()),
                ('about_name', models.CharField(max_length=100)),
                ('about_location', models.CharField(max_length=100)),
                ('about_loc_status', models.CharField(max_length=100)),
                ('about_resume_pdf', models.FileField(upload_to='about_me/files/')),
            ],
        ),
    ]
