# Generated by Django 4.1.5 on 2023-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_images', models.ImageField(upload_to='edu_images/images')),
                ('edu_url', models.URLField(blank=True)),
            ],
        ),
    ]
